ALTER TABLE user
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE comment
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE service
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE customer
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE discovery_method
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;